language: python
matrix:
  include:
  - python: 3.7.1
  dist: xenial
  sudo: true

install:
- pip install pipenv
- cd server && pipenv install --dev

script:
- pytest --cov-report=term --cov=habits --cov-fail-under=100 tests/

after_success:
- codecov
